version: "3.3"

services:
  php8:
    # container_name: php8
    depends_on:
      - db
    volumes:
      - ./home:/var/www/nobody
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      HOME: /var/www/nobody
